### ISSUE TITLE
pretrained model download issue

### ISSUE THREAD

**Issue by dndmania** [abhuse/pytorch-efficientnet#2]
hi 

When downloading the pre-trained model,
urllib.error.HTTPError: HTTP Error 401: Unauthorized
An error has occurred.

Is there any URL that I can receive the pre-trained model manually?

thanks for your code

**Comment by abhuse** [comment]
Error 401 should be fixed now.
In case you want to manually download weights: [https://1drv.ms/f/s!AtiQpw9TccfibK_GhNOYeDmuLww](https://1drv.ms/f/s!AtiQpw9TccfibK_GhNOYeDmuLww)
